name: 'Publish Archive'

on:
  schedule:
   - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  publish_archive_job:
    runs-on: ubuntu-latest
    name: Publish zulip-archive in GitHub pages
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: gh-pages
    - name: Run archive
      id: archive
      uses: tisonkun/zulip-archive-1@patch-1
      with:
        zulip_organization_url: ${{ secrets.zulip_organization_url }}
        zulip_bot_email: ${{ secrets.zulip_bot_email }}
        zulip_bot_key: ${{ secrets.zulip_bot_key }}
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        delete_history: true
        archive_branch: gh-pages
